Repository LABS-Codepath/GameOn, pull requests merged in 2022-08, with the labels that each got.

#68 Updated Events, Profile, and Event Details
  gameon-ui/src/components/App/App.jsx
  gameon-ui/src/components/Events/CreateEventForm.jsx
  gameon-ui/src/components/Events/EventCard.jsx
  gameon-ui/src/components/Events/EventDetails.jsx
  gameon-ui/src/components/Events/EventFeed.jsx
  gameon-ui/src/components/Events/EventPage.jsx
  gameon-ui/src/components/Events/EventRegistration.jsx
  gameon-ui/src/components/Footer/Footer.jsx
  gameon-ui/src/components/NavBar/NavBar.jsx
  gameon-ui/src/components/Posts/PostsFeed.jsx
  gameon-ui/src/components/ProfilePage/ProfileDetails.jsx
  gameon-ui/src/components/ProfilePage/ProfilePage.jsx
  gameon-ui/src/components/ProfilePage/UserPreviousEvents.jsx
  gameon-ui/src/components/ProfilePage/UserUpcomingEvents.jsx
  gameon-ui/src/components/Search/Search.jsx
Labels: enhancement

#69 event details updated
  gameon-ui/src/components/Events/EventDetails.jsx
  gameon-ui/src/components/Events/EventRegistration.jsx
  gameon-ui/src/components/Home/Home.jsx
  gameon-ui/src/components/Posts/Posts.jsx
  gameon-ui/src/components/Posts/PostsFeed.jsx
  gameon-ui/src/components/Posts/PostsForm.jsx
Labels: enhancement

#70 Registration bug fixes
  gameon-api/app.js
  gameon-api/models/user.js
  gameon-api/routes/user.js
  gameon-ui/src/components/App/App.jsx
  gameon-ui/src/components/Events/EventRegistration.jsx
  gameon-ui/src/components/NavBar/NavBar.jsx
  gameon-ui/src/components/Posts/PostReply.jsx
  gameon-ui/src/components/Posts/Posts.jsx
  gameon-ui/src/components/ProfilePage/ProfileDetails.jsx
  gameon-ui/src/components/UsersProfilePage/UsersPosts.jsx
  gameon-ui/src/components/UsersProfilePage/UsersPostsFeed.jsx
  gameon-ui/src/components/UsersProfilePage/UsersPreviousEvents.jsx
  gameon-ui/src/components/UsersProfilePage/UsersProfileDetails.jsx
  gameon-ui/src/components/UsersProfilePage/UsersProfilePage.jsx
  gameon-ui/src/components/UsersProfilePage/UsersUpcomingEvents.jsx
  gameon-ui/src/services/apiClient.js
Labels: enhancement

#75 Homepage frontend
  gameon-ui/src/components/Footer/About.jsx
  gameon-ui/src/components/Footer/Footer.jsx
  gameon-ui/src/components/Home/Home.jsx
  gameon-ui/src/components/NavBar/NavBar.jsx
Labels: bug

#76 error checking to all forms
  gameon-ui/src/components/EditProfile/EditProfile.jsx
  gameon-ui/src/components/Events/CreateEventForm.jsx
  gameon-ui/src/components/LoginPage/LoginPage.jsx
  gameon-ui/src/components/RegisterPage/RegisterPage.jsx
  gameon-ui/src/components/Search/Search.jsx
Labels: enhancement

#77 Registration bug fixes
  gameon-ui/src/components/Events/EventDetails.jsx
  gameon-ui/src/components/Events/EventRegistration.jsx
Labels: enhancement

#79 added error checking on some of the models in the backend
  gameon-api/models/events.js
  gameon-api/models/games.js
  gameon-api/models/user.js
Labels: enhancement

#80 Homepage frontend
  gameon-ui/src/components/Events/EventFeed.jsx
  gameon-ui/src/components/Footer/Footer.jsx
  gameon-ui/src/components/Hero/Hero.jsx
  gameon-ui/src/components/NavBar/NavBar.jsx
Labels: documentation

#81 Homepage frontend
  gameon-ui/src/components/Events/EventDetails.jsx
  gameon-ui/src/components/Footer/About.jsx
  gameon-ui/src/components/Footer/Footer.jsx
  gameon-ui/src/components/NavBar/NavBar.jsx
  gameon-ui/src/components/Posts/Posts.jsx
  gameon-ui/src/components/Posts/PostsFeed.jsx
Labels: bug, documentation

#82 Homepage frontend
  gameon-ui/src/components/App/App.jsx
  gameon-ui/src/components/EditProfile/EditProfile.jsx
  gameon-ui/src/components/Events/EventFeed.jsx
  gameon-ui/src/components/Footer/About.jsx
  gameon-ui/src/components/Footer/Footer.jsx
  gameon-ui/src/components/NavBar/NavBar.jsx
  gameon-ui/src/components/Posts/PostReply.jsx
  gameon-ui/src/components/Posts/Posts.jsx
  gameon-ui/src/components/Posts/PostsFeed.jsx
  gameon-ui/src/components/Posts/PostsForm.jsx
  gameon-ui/src/components/Search/Search.jsx
  gameon-ui/src/components/UsersProfilePage/UsersProfileDetails.jsx
  gameon-ui/src/components/UsersProfilePage/UsersProfilePage.jsx
  gameon-ui/src/contexts/media/Logo.jpg
  gameon-ui/src/contexts/media/Logo.jpg~
  gameon-ui/src/contexts/media/Logo.png
  gameon-ui/src/contexts/media/Logo.png~
  gameon-ui/src/contexts/media/colors.txt
  gameon-ui/src/contexts/media/elmo-burning.gif
  gameon-ui/src/contexts/media/evo.jpg
  gameon-ui/src/contexts/media/evo2.jpg
  gameon-ui/src/contexts/media/indigobg.jpg
  gameon-ui/src/contexts/media/tournament.jpg
Labels: documentation

#83 Switching branch. Last pull request from this branch
  gameon-ui/src/components/Posts/PostReply.jsx
  gameon-ui/src/components/UsersProfilePage/UsersPosts.jsx
  gameon-ui/src/components/UsersProfilePage/UsersProfilePage.jsx
Labels: documentation

#86 Registration form changes
  gameon-api/models/events.js
  gameon-api/models/games.js
  gameon-api/routes/games.js
  gameon-ui/src/components/Events/EventDetails.jsx
  gameon-ui/src/components/Events/EventRegistration.jsx
Labels: enhancement

#87 Homepage frontend
  gameon-ui/src/components/Events/EventFeed.jsx
  gameon-ui/src/components/Footer/About.jsx
  gameon-ui/src/components/UsersProfilePage/UsersProfilePage.jsx
Labels: bug, documentation

#89 Update reflection3.md
  reflections/reflection3.md
Labels: documentation

#92 Logo sizing fix to main
  gameon-ui/src/components/Footer/About.jsx
  gameon-ui/src/components/NavBar/NavBar.jsx
  gameon-ui/src/contexts/media/Logo-fixed.png
  gameon-ui/src/services/apiClient.js
Labels: enhancement
